name: apkify
base: core20
version: '0.666'
summary: .apk builder from web assets

description: |
  a tools to building, signing, and align .apk and .aah apps from web assets.

grade: stable
confinement: devmode

apps:
  
  apkify:
    command: snap
    plugs:
      - x11
      - home
      - network
      - wayland
      - desktop
      - desktop-legacy

parts:

  stage-packages:
    plugin: nil
    stage-packages:
      - gradle
      - imagemagick
      - build-essential
      - openjdk-11-jre-headless
      - openjdk-8-jdk-headless

  build-packages:
    plugin: nil
    after:
      - stage-packages
    build-packages:
      - android-sdk